variables:
  - name: 'repositoryName' # Name of the repository
    value: 'ameyapatOrg/pipelinetest'
  - name: 'repositoryBranch' # Name of the branch where version number will be updated for files that contain version number.
    value: 'master'
  - name: 'isMain'
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - CHANGELOG.md

pr: none

resources:
  repositories:
  - repository: msalRepository
    type: github
    endpoint: 'ameyapat'
    name: $(repositoryName)
    ref: $(repositoryBranch)

jobs:
- job: PipelineTestJob
  displayName: Pipeline Test for trigger check
  #condition: and(eq(variables.isMain, true),ne(variables['Build.Reason'], 'PullRequest'))
  pool:
    vmImage: 'macOS-latest'
    timeOutInMinutes: 20

  steps:
  - checkout: msalRepository
    clean: true
    submodules: true
    fetchDepth: 1
    persistCredentials: false

#  - task: InstallSSHKey@0
#    inputs:
#      knownHostsEntry: 'ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=='
#      sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDI6UC8+khkEQ5q2TGpeXgRZKFcvGgWHMZQT5a0AJPeWdeT9EkYZWNBkRm2VCnsxGCn7hlGFEyu2WAPalrlUipW0fJoo5Y9Da2VqvQIC0rnn4Ph9mtvUQl9BdciH7G37miRNVc2hRFnYzFxhrR6aH0k4GScXrvLmrW4pG6Tn1pabXsxfYFhJ4mtpr3UWmhui1MVAbGp0xftLxojsRqgRU+BwCJBTEEkIUioFdAhvyMVFkJG8xpqMK3xDgcksb+a9CgTGL/1FoeQ9XKg0f8brMKKhuA8LTJzP/y86UP7WXgIKSzFJMN+Gi8ljvjPPBT2mvhbnwJV3YDkca2T7IzcNA1C1kLu3bn0/doy/cHj22FL+H7Z8uY6kyz7S+om9VfftiFpE6VB/+YaACCUna/Go0FKRtqpzNi4uOc0tCHrdZv32l8OXom8rvlfP0kGQBeJcwC2lYyy1W8Kl7fZIpFILPLXe8HWgGs0dPevDfYEjWRJxRqpevr9/2JTxkCyLU3+kq8= ameyapatil@CASTROFES.northamerica.corp.microsoft.com'
#      sshKeySecureFile: 'id_rsa'
#      addEntryToConfig: true
#      configHostAlias: 'ameyaOrgKey'
#      configHostname: 'github.com'
  
  - task: Bash@3
    displayName: git push
    inputs:
      targetType: 'inline'
      script: |
        rm -rf release-notes.md
        rm -rf cc-release-notes.md
        git config --global user.email "ameya.v.patil@gmail.com"
        git config --global user.name "ameyaPipeline"
        git config --list
        git fetch origin $(repositoryBranch)
        git checkout FETCH_HEAD
        git checkout -b update-package
        if [ ! -e Package.swift ]; then
            echo -e "// swift-tools-version:5.3\n" >> Package.swift
            cat >> Package.swift << EOF
        import PackageDescription

        let package = Package(
          name: "MSAL",
          platforms: [
                .macOS(.v10_12),.iOS(.v11)
          ],
          products: [
              .library(
                  name: "MSAL",
                  targets: ["MSAL"]),
          ],
          targets: [
              .binaryTarget(name: "MSAL", url: "https://github.com/$(repositoryName)/releases/download/releaseTag1.2.3/MSAL.zip", checksum: "abcdefabcdef1234567890abcdef1234567890abcdef1234567890abcdef1234")
          ]
        )
        EOF
        fi
        perl -i -pe's/releases\/download\/[0-9a-zA-Z\.].+\//releases\/download\/$(Build.BuildId)\//' Package.swift
        git add Package.swift
        author=$(git log -1 --pretty=format:'%an <%ae>')
        echo "Source branch $(Build.SourceBranchName) $(Build.SourceBranch)"
        echo "Commiting as ${author}"
        #ssh -T git@github.com
        git commit -a -m "Updating MSAL framework checksum & url [skip ci]" -q --author="${author}"
        git checkout $(repositoryBranch) -q
        git merge update-package -q
        git push $(repositoryBranch)
        git branch -d update-package -q
      workingDirectory: '$(Build.SourcesDirectory)'
      failOnStderr: true
      noProfile: false
      noRc: false
      
